// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47kjj7-_uzij6iPaAS20IYfu6V9rKAK0',
    appId: '1:319393157594:web:41b9c8a7ff1c190a66b0e3',
    messagingSenderId: '319393157594',
    projectId: 'nyxia-app',
    authDomain: 'nyxia-app.firebaseapp.com',
    storageBucket: 'nyxia-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy4KaqGnOoDPOeYErISh18a3roQecUCLs',
    appId: '1:319393157594:android:4123c78abd14efe666b0e3',
    messagingSenderId: '319393157594',
    projectId: 'nyxia-app',
    storageBucket: 'nyxia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk-LV0k_bOwqn9YoaswG5MN3kl-fUqEB8',
    appId: '1:319393157594:ios:b530f6611194e82966b0e3',
    messagingSenderId: '319393157594',
    projectId: 'nyxia-app',
    storageBucket: 'nyxia-app.firebasestorage.app',
    iosClientId:
        '319393157594-7vmm30hj4arvutb0eqo0i7jdspat5m5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyxia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk-LV0k_bOwqn9YoaswG5MN3kl-fUqEB8',
    appId: '1:319393157594:ios:b530f6611194e82966b0e3',
    messagingSenderId: '319393157594',
    projectId: 'nyxia-app',
    storageBucket: 'nyxia-app.firebasestorage.app',
    iosClientId:
        '319393157594-7vmm30hj4arvutb0eqo0i7jdspat5m5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.nyxia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA47kjj7-_uzij6iPaAS20IYfu6V9rKAK0',
    appId: '1:319393157594:web:01fd126dd057394266b0e3',
    messagingSenderId: '319393157594',
    projectId: 'nyxia-app',
    authDomain: 'nyxia-app.firebaseapp.com',
    storageBucket: 'nyxia-app.firebasestorage.app',
  );
}
